### PR TITLE
Added deformation task to runScript to deform an IGES file.

### PR DESCRIPTION
**Pull request by bernardopacini**
This PR adds a task to the `PROWIM_WING_PROPELLER` tutorial to deform an IGES file representation of the wing given the design variable values at the 5th objective function evaluation when using SLSQP (saved in a JSON file).

The files to generate the IGES file for the wing are *not* included in this PR but the provided IGES file must be downloaded and used.

Note: this update requires an update to pyGeo to https://github.com/mdolab/pygeo/commit/1166d71c783e2bcff8a8754d6a76f2b570589d13 or newer.

### CODE REVIEW

**Comment by bernardopacini** [comment]
The needed JSON and IGES files are not included in this PR as they are large files. Should we add them here regardless or package them with the other tutorial files that are downloaded using the preprocessing script?

**Comment by bernardopacini** [comment]
Do we want to add documentation for this task specifically or leave it as an example in the docs without extra explanation?

**Comment by friedenhe** [comment]
Looking good! Can you create a new folder (deformGeo) and add the files to generate the wing IGES along with an example of JSON file for deformed design variables? Also, in tutorials/Prowim_Wing_Propeller, can you create a bash script (deformGeo.sh) such that users can run this script and get the deformed geometry.

**Comment by bernardopacini** [comment]
I just added in those features. Would you like me to update the documentation and add in a paragraph explaining how this task works?

**Review by friedenhe — COMMENTED** [review]
> I just added in those items. Would you like me to update the documentation and add in a paragraph explaining how this task works?

Yes, a short paragraph explaining how this works will be very helpful. I will merge it when the reg tests pass.

**Pull request merged**
